### ISSUE TITLE
Robothor objectnav debug

### ISSUE THREAD

**Issue by YicongHong** [allenai/embodied-clip#10]
Hi Apoorv,
May I ask for your suggestion how to debug with the Robothor ObjectNav codebase? Such as setting a breakpoint or use python pdb?

**Comment by apoorvkh** [comment]
I personally haven't used any sophisticated methods to debug AllenAct / RoboTHOR. Maybe you should ask about this in the official repositories.

I would just try to make sure you're able to run the baseline experiments, then make one change at a time and ensure that each works. If something crashes, I do something similar to a breakpoint and print out the variables I'm interested in.
