### ISSUE TITLE
pointnav imagenet pre-trained model (pointnav-rgb-imagenet.150M.pth) does not fit for the network

### ISSUE THREAD

**Issue by JeffreyYH** [allenai/embodied-clip#13]
Hi, we I use imagenet pre-trained model to run evaluation, it shows the following error.

`RuntimeError: Error(s) in loading state_dict for PPO:
        Unexpected key(s) in state_dict: "actor_critic.net.visual_encoder.backbone.conv2.weight", "actor_critic.net.visual_encoder.backbone.bn2.weight", "actor_critic.net.visual_encoder.backbone.bn2.bias", "actor_critic.net.visual_encoder.backbone.bn2.running_mean", "actor_critic.net.visual_encoder.backbone.bn2.running_var", "actor_critic.net.visual_encoder.backbone.bn2.num_batches_tracked", "actor_critic.net.visual_encoder.backbone.conv3.weight", "actor_critic.net.visual_encoder.backbone.bn3.weight", "actor_critic.net.visual_encoder.backbone.bn3.bias", "actor_critic.net.visual_encoder.backbone.bn3.running_mean", "actor_critic.net.visual_encoder.backbone.bn3.running_var", "actor_critic.net.visual_encoder.backbone.bn3.num_batches_tracked". 
        size mismatch for actor_critic.net.visual_encoder.backbone.conv1.weight: copying a param with shape torch.Size([32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 3, 7, 7]).
        size mismatch for actor_critic.net.visual_encoder.backbone.bn1.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for actor_critic.net.visual_encoder.backbone.bn1.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for actor_critic.net.visual_encoder.backbone.bn1.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for actor_critic.net.visual_encoder.backbone.bn1.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
Exception ignored in: <function VectorEnv.__del__ at 0x7f2b0c2ff5f0>`

Maybe the model is not compatable to the network?

**Comment by apoorvkh** [comment]
Thanks for your interest! You can open an issue at [allenai/allenact](https://github.com/allenai/allenact) and you will get support there, as these changes have been upstreamed into the official AllenAct repo and are maintained there.
