### ISSUE TITLE
How to add new models apart from CLIP?

### ISSUE THREAD

**Issue by shivam-chandhok** [allenai/embodied-clip#14]
Hi guys,

Thanks for this amazing work.
I wanted to know if there is a ReadMe/ instructions on how to add new models (apart from CLIP) and do the evaluation.

Thanks :)

**Comment by apoorvkh** [comment]
You can probably look through this PR to see how I modified AllenAct and added the CLIP models. You can probably do something very similar.

https://github.com/allenai/allenact/pull/329

If you are interested in Habitat, you can dig through my code changes in the `habitat` branch of this repo: https://github.com/allenai/embodied-clip/compare/ac4339ed7e9bafb5e45fee9c5cf68095f40edee2...habitat
I had written the Habitat training/eval instructions here: https://github.com/allenai/embodied-clip/blob/main/readme_files/baselines_habitat.md

Hope that helps.
