### ISSUE TITLE
training&pretraining

### ISSUE THREAD

**Issue by snow2white** [allenai/embodied-clip#2]
Excuse me
  I have observed that 60 processes are used when reading data, can I change to 5 processes , because my gpu is only 3060. Does this only affect the convergence time and not the final effect ?

  At the same time I have another question, because I train on docker, the screen transfer speed is too slow is it possible to cancel the gui. so can i close the gui screen?

  Finally, may I ask which file of the code your clip-vn-navigation-model file is in? I have download “objectnav-robothor-clip-rn50.130M.pt” I printed the weights of this model and looked at the size of the model, but I found the size of the model and the name of each layer of the network, and found that this is not the same as the clip model

**Comment by apoorvkh** [comment]
Hey, sorry for the delayed response. You should be able to reduce the number of processes, but this will increase training time. Converging at the same results may take longer than 30x (= 60 / 5) original training time.

I don't think you can close the GUI screen, but you can run AI2-THOR in headless mode, so screens won't appear. Please see more details at [AllenAct Distributed ObjectNav Tutorial](https://allenact.org/tutorials/distributed-objectnav-tutorial).

I am not sure what you are referring to with the particular keyword `clip-vn-navigation-model`. The weights in `objectnav-robothor-clip-rn50.130M.pt` don't correspond to CLIP's image encoder network, but the whole embodied agent pipeline (including the visual encoder, but also the RNN and actor/critic networks). Please refer to Figure 2 of our paper.
