### ISSUE TITLE
Repetitive scene/episode on different GPUs 

### ISSUE THREAD

**Issue by YicongHong** [allenai/embodied-clip#3]
Hi There,

Thanks helps for the amazing work and thanks a lot for sharing the code. I have a question regarding the ObjNav data loading, it seems that during the DDPPO training (I am using multiple GPUs on a single node), all different GPUs are getting the same scene splits and they are loading the same episode in the same order. I tried to print out the scene and episode ids in the main step loop:

> rank: 1 episode: 40828 scene: D7N2EKCX4Sj.glb
> rank: 1 episode: 8453 scene: mJXqzFtmKg4.glb
> rank: 0 episode: 40828 scene: D7N2EKCX4Sj.glb
> rank: 0 episode: 8453 scene: mJXqzFtmKg4.glb

I am wondering does the code do this for any reason on purpose?

Thanks

**Comment by apoorvkh** [comment]
Hey, thanks and so sorry for the delayed response!

I'm not sure about the details of the print artifacts you've provided, however if you use our codebase in the default configuration, we use DD-PPO and the scenes are split across the GPUs. So the GPUs don't train agents on the same sets of episodes and scenes. This repository is a direct fork of the AllenAct codebase, which you can take a look at for further details. Hopefully that helps!
