### ISSUE TITLE
version about habitat-sim in object nav task

### ISSUE THREAD

**Issue by xuexidi** [allenai/embodied-clip#4]
hello, thanks for your wonderful work!

In Habitat ObjectNav branch (https://github.com/allenai/embodied-clip/blob/main/readme_files/baselines_habitat.md），I only see:

```
git clone -b habitat --single-branch https://github.com/allenai/embodied-clip.git embclip-habitat
cd embclip-habitat
```
to use `habitat-lab`.

But I didn't see any version of `habitat-sim` installed (`habitat-lab` relys on `habitat-sim`), I have never used habitat simulator (I have no experience in this). Please tell me what version of `habitat-sim` is installed in your work, thank you very much!

**Comment by apoorvkh** [comment]
Hey, thanks for your interest!

Please take a look at that [README file](https://github.com/allenai/embodied-clip/blob/main/readme_files/baselines_habitat.md) again. You will see that the next instruction (after cloning) is to run:
```bash
conda env create --name embclip-habitat
conda activate embclip-habitat
```

This will install all Python requirements, including `habitat-sim=0.1.7` from the [environment.yml](https://github.com/allenai/embodied-clip/blob/habitat/environment.yml#L13) file.

**Comment by xuexidi** [comment]
> Hey, thanks for your interest!
> 
> Please take a look at that [README file](https://github.com/allenai/embodied-clip/blob/main/readme_files/baselines_habitat.md) again. You will see that the next instruction (after cloning) is to run:
> 
> ```shell
> conda env create --name embclip-habitat
> conda activate embclip-habitat
> ```
> 
> This will install all Python requirements, including `habitat-sim=0.1.7` from the [environment.yml](https://github.com/allenai/embodied-clip/blob/habitat/environment.yml#L13) file.

@apoorvkh 
Thanks！
I have successfully run the Habitat ObjectNav training code you provided.
