### ISSUE TITLE
ObjectNav performance

### ISSUE THREAD

**Issue by YicongHong** [allenai/embodied-clip#9]
Hi Apoorv,
I have rerun the training of Habitat-ObjNav with the default configurations, trying to reproduce your results. I found that for the `val-mini` set which is evaluated during training, the SR peaks at 150M frames (16.67%), but then it drops to 0%. Does this behavior also appear in your experiments?
I also noticed that you have provided the pre-trained model of `objectnav-rgb-clip` at the 175M step, does it mean that you use the `val-mini` or `val` set to choose the best model? Thanks!

![1661470845368](https://user-images.githubusercontent.com/33921340/186787472-87236f37-d7f8-4885-93f7-a7edd159e7f9.jpg)

**Comment by apoorvkh** [comment]
Hi, no, I didn’t observe this behavior during training. The `val-mini` metrics peaked at 175M steps, but did not drop significantly after this. And, we saw that this checkpoint was best according to both the `val-mini` and `val` sets.

**Comment by apoorvkh** [comment]
It might also be a good idea to run evaluation on the checkpoint I have provided to see if you are able to reproduce the metrics from our paper.

**Comment by YicongHong** [comment]
Hi Apoorv, thanks for pointing this out.
A small question: I am testing the evaluation on the `val-unseen` split, but I found the speed is extremely slow -- eval a single checkpoint could take upto **20+ hours**. I know that there are lots of episodes and the `max_allowed_steps` is large and it takes time for the simulator to renender the environment / move the agent, but I have already set `NUM_ENVIRONMENTS=11` (equals to the #val-unseen envs) and `use_cuda` and disabled `generate_videos`. I also observe that the GPU utilization is 0% a large portion of time. Does this also happened on your side? Any suggestions how to speed things up?
Many thanks!

___________________________________

Update: 
It turns out that 90% of the time was spent on calling the function `envs.current_episodes()` twice at each step, which re-reads the large dataset file but only returns `episode_id` and `scene_id`, while this information can be easily obatined with the `observations`, simply by modifying a few lines of code in `habitat/core/embodied_task.py`. Now it only takes 1~2 hours to finish an epoch (tho it still sounds pretty long :)

**Comment by apoorvkh** [comment]
Hi Yicong, glad you were able to resolve that issue! It certainly takes a while to evaluate checkpoints, although my experience was closer to a few hours rather than 20. If you would like to open a PR for the habitat branch with this fix, I will consider merging it.

**Comment by YicongHong** [comment]
Hi Apoorv, I got some new results which really confuse me.

I run a very simple baseline which uses CLIP for RGB and PointNav-Resnet for Depth features (this is the only thing I changed in the code), I use the same policy network as in your paper, and the default DDPPO configurations. I trained the exactly same model twice for 250M steps, the two results have 7% discrepency (15% vs 22% success rate) on the val-unseen data.
Do you have similar observation in your experiments? I am wondering if such instability is due to the DDPPO method or the ObjectNav data? From the recent publications on Object Nav, 7% is a huge gap and 22% success rate is already SoTA. With such instability I am really not sure how to move on to further experiment.

Any ideas? Any suggestions how I can make the DDPPO training more stable?

Thanks!

**Comment by apoorvkh** [comment]
Hi, sorry to miss this earlier. I'm not sure how to make DD-PPO training more stable, however I did see fluctuations in model performance. I recommend that you save checkpoints for every 25M or 50M steps and select the one with the best validation metrics. The checkpoint at 250M steps is not necessarily the best performing model. Hope that helps.
